name: GTest CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t qem-simplifier .

      - name: Run Tests in Docker
        run: |
          docker run --rm qem-simplifier ./build/QEMSimplifierTests
