name: GTest CI

on:
  push:
    branches: [github-actions]
  pull_request:
    branches: [github-actions]

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
        build_type: [CPU, Metal]
        suite: [ParserTests, QEMSimplifierUtilsTests, QEMSimplifierTests]
        exclude:
          - runs-on: ubuntu-latest
            build_type: Metal

    name: Run ${{ matrix.build_type }} on ${{ matrix.runs-on }} - ${{ matrix.suite }}

    runs-on: ${{ matrix.runs-on }}

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Cache
      - name: Cache CMake Files
        uses: actions/cache@v3
        with:
          path: |
            build-${{ matrix.build_type }}
            ~/.cmake/packages
          key: cmake-cache-${{ matrix.build_type }}-${{ runner.runs-on }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            cmake-cache-${{ matrix.build_type }}-${{ runner.runs-on }}-

      # Step 3 (CPU): Install System Dependencies
      - name: Install System Dependencies
        if: matrix.runs-on == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            git \
            wget \
            libglfw3-dev \
            libglew-dev \
            freeglut3-dev \
            libx11-dev \
            libxi-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev

      # Step 3 (Metal): Install System Dependencies
      - name: Install System Dependencies
        if: matrix.runs-on == 'macos-latest'
        run: |
          brew update
          brew install --formula cmake glfw glew freeglut

      - name: Print CMake version
        run: cmake --version

      - name: Print Python version
        run: python3 --version

      # Step 4: Configure CMake
      - name: Configure CMake
        run: |
          mkdir -p build-${{ matrix.build_type }} && cd build-${{ matrix.build_type }}
          if [ "${{ matrix.build_type }}" == "Metal" ]; then
            cmake -DUSE_METAL=ON -DCMAKE_BUILD_TYPE=Release ..
          else
            cmake -DCMAKE_BUILD_TYPE=Release ..
          fi

      # Step 5: Build the Project
      - name: Build the Project
        run: |
          cmake --build build-${{ matrix.build_type }} -- -j$(nproc)

      # Step 6: Run the Test Suite
      - name: Run Test Suite
        run: |
          cd build-${{ matrix.build_type }}
          ctest --output-on-failure --tests-regex "${{ matrix.suite }}"
